# Generated by Django 4.1 on 2022-10-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plants',
            new_name='Fruits',
        ),
    ]
