# Generated by Django 4.1 on 2022-10-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_rename_plants_fruits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruits',
            old_name='plant_name',
            new_name='fruit_name',
        ),
    ]
