# Generated by Django 4.1 on 2022-10-25 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0003_rename_plant_name_fruits_fruit_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycart',
            old_name='plant',
            new_name='fruit',
        ),
    ]
